### ISSUE TITLE
Possible regression related to permissions on DrvFs

### ISSUE THREAD

**Issue by biwizit** [Zythyr/RbuWSL#1]
Hello,

Thank you for this very good job !

But I wanted to let you know that I had to update the mount command to make this script OK, when using latest version/build (1809/17763.195) for Windows 10 / WSL and latest Ubuntu distro (18.04.1 LTS).

I think it is due to a regression related to permission on DrvFs described in the following ticket : https://github.com/Microsoft/WSL/issues/3187#issuecomment-388904048 (and associated discussions : https://github.com/Microsoft/WSL/issues/2770 and https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/).

Your initial mount command (_sudo mount -t drvfs $1: $2_) gave me a lot of "rsync: chgrp _file_name_ failed: Operation not permitted (1)" and the next rsync command had to start the job from scratch (ie to synchronize **all** the data again)... 

With _sudo mount -t drvfs $1: $2 -o uid=1000,gid=1000,metadata_  everything is perfectly fine.

Regards.

**Comment by Zythyr** [comment]
@biwizit Thank for reporting this issue. Recently I have also been facing similar issues Thank for sharing the related issues on WSL issue page. I will be pushing a fix soon.

**Comment by Zythyr** [comment]
@biwizit  The latest commit https://github.com/Zythyr/RbuWSL/commit/695e83b2f9acce2b449875466c88122980ec1783 should fix the issues you reported.
